# main menu
[[main]]
name = "Thuis"
url = ""
weight = 1

[[main]]
name = "Over"
url = "about/"
weight = 2

[[main]]
weight = 4
name = "Paginas"
hasChildren = true

  [[main]]
  parent = "Paginas"
  name = "Blog Details"
  url = "blog/post-1/"
  weight = 1

  [[main]]
  parent = "Paginas"
  name = "Algemene voorwaarden"
  url = "terms-and-conditions/"
  weight = 7

[[main]]
name = "Contact"
url = "contact/"
weight = 5


# footer menu
[[footer]]
name = "Over"
url = "about/"
weight = 1

[[footer]]
name = "Privacy beleid"
url = "privacy/"
weight = 3

[[footer]]
name = "Algemene voorwaarden"
url = "terms-and-conditions/"
weight = 4
