#################### default parameters ################################
# favicon
favicon = "images/favicon.png"
# logo
logo = "images/logo.svg"
# use `x` with logo_width, example: "100x"
logo_width = "360x"
# logo text will only show when logo is missing.
logo_text = "CloudAlert"
# OpenGraph / Twitter Card metadata
description = "CloudAlert - Alarmeren vanuit de Cloud"
author = "CloudAlert B.V."
image = "images/logo.png"                # this image will be used as fallback if a page has no image of its own

# footer information
footer_info = "Flexibele Cloud gebaseerde Alarmeringen. Sluit je hardware, software of machines aan op onze cloud en ontvang de alerts daarvan direct!"

# contact form action
contact_form_action = "https://formspree.io/f/xnqyepwn" # contact form works with https://formspree.io

# copyright
copyright = "CloudAlert B.V. © 2023"

# custom script on header, example: custom_script= "<script>console.log(\"Hello World\")</script>"
custom_script = ""

# Main Sections
mainSections = ["pages"]

# reading time for blog posts
reading_time = true

# contact information
[contact_info]
address = "Harlingen, Nederland"
phone = ["085 - 087 62 60"]
email = ["info@cloudalert.eu"]

# imaging processing
[imaging]
# Default JPEG or WebP quality setting. Default is 100.
quality = 100

# Preloader
[preloader]
enable = true
preloader = "images/favicon.png" # use jpg, png, svg or gif format.

# Navigation button
[navigation_button]
enable = true
label = "Neem contact met ons op!"
link = "/nl/contact/"

# cookies
[cookies]
enable = true
expire_days = 2
content = "We gebruiken cookies. Door op Accepteren te klikken ga ja akkoord met het gebruik hiervan."
button = "Accepteren"

# call-to-action
[cta]
enable = true
title = "Start nu met CloudAlert!"
content = "Maak een gratis account en start direct met het versturen en ontvangen van alarmeringen!."
button = "Registreer nu."
button_link = "https://dashboard.cloudalert.eu/nl/register/"

############################# social site ########################
[[social]]
title = "Facebook"
icon = "lab la-facebook-f" # https://icons8.com/line-awesome
link = "#!"

# [[social]]
# title = "AndromedaTweet"
# icon = "lab la-twitter"  # https://icons8.com/line-awesome
# link = "#!"

[[social]]
title = "LinkedIn"
icon = "lab la-linkedin-in" # https://icons8.com/line-awesome
link = "https://www.linkedin.com/company/93145134"

# [[social]]
# title = "AndromedaPin"
# icon = "lab la-pinterest" # https://icons8.com/line-awesome
# link = "#!"
