name = "CloudAlert"
license = "MIT"
licenselink = "https://github.com/CloudAlert/company-Website/blob/master/LICENSE"
description = "CloudAlerts compny website based on the andromeda-light hugo theme."
homepage = "https://github.com/CloudAlert/company-Website/"
features = ['responsive']
min_version = "0.110.0"

[author]
name = "CloudALert"
homepage = "https://cloudAlert.eu/"
